version: "3.7"

services:
  db:
    container_name: db
    image: postgres:11.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - $PG_PORT:$PG_PORT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    command: python manage.py runserver $BIND_TO_HOST:$WEB_PORT
    ports:
      - $WEB_PORT:$WEB_PORT
    volumes:
      - './tracker_api:/code'
      - './requirements:/code'
    depends_on:
      - db
    env_file: .env
  web:
    container_name: tracker-web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'
    environment:
      - CHOKIDAR_USEPOLLING=true


volumes:
  postgres_data: