version: "3.7"

services:
  db:
    container_name: db
    image: postgres:11.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - $PG_PORT:$PG_PORT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver $BIND_TO_HOST:$WEB_PORT
    ports:
      - $WEB_PORT:$WEB_PORT
    volumes:
      - ./tracker:/code
    depends_on:
      - db
    env_file: .env


volumes:
  postgres_data: