version: "3.7"

services:
  db:
    image: postgres:11.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - $PG_PORT:$PG_PORT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  web:
    image: web
    build: .
    command: python manage.py migrate
    ports:
      - $WEB_PORT:$WEB_PORT
    volumes:
      - .:/app
    depends_on:
      - db
    env_file: .env

volumes:
  postgres_data:

# to enter a docker container 
# docker ps
# docker exec -t -i <container_id> bash