# Generated by Django 2.1.8 on 2019-07-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='measured_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weight',
            name='scale_calc_body_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='scale_calc_lbm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
