# Generated by Django 2.1.8 on 2019-07-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
